all:
  children:
    docker_hosts:
      hosts:
        localhost:
          ansible_connection: local
        
        azure-vm:
            ansible_host: 131.163.97.65
            ansible_user: Bill
            ansible_password: Devops_2026_ergasia
            ansible_become_password: Devops_2026_ergasia

    vm_hosts:
      hosts:
        localhost:
          ansible_connection: local
          
        azure-vm:
            ansible_host: 131.163.97.65
            ansible_user: Bill
            ansible_password: Devops_2026_ergasia
            ansible_become_password: Devops_2026_ergasia
